
module.exports = {
  SCHEMA_DBO: "dbo.",
  SCHEMA_SURVEY: "Survey.",
  SCHEMA_HUMANRESOURCES: "HumanResources.",

  //***********************PARAMS*************************//
  PARAM_BIRTHDAY_CITY_ID:"birth_city_id",
  PARAM_QUALIFACTION_ID:"qualification_id",
  PARAM_FLOOR_EXTENSION_ID:"floor_extension_id",
  PARAM_EMPLOYEE_STATUS_ID:"employee_status_id",
  PARAM_EMPLOYEE_NAME:"employee_name",
  PARAM_EMPLOYEE_SHORT_NAME:"employee_short_name",
  PARAM_BIRTHCITY_ID:"birth_city_id",
  PARAM_BIRTHDATE:"birthdate",
  PARAM_HIREDATE:"hire_date",
  PARAM_EMPLOYEEE_ID:'emp_id',
  PARAM_QUALIFICATION_ID:"qualification_id",
  PARAM_ANNIVERSARY_DATE:"anniversary_date",
  PARAM_PRIMARY_EMAIL_ID:"primary_email_id",
  PARAM_PRIMARY_PHONE_NO:"primary_phone_number",
  PARAM_TRAVEL_PREFERANCE_ID:"travel_preferance_id",
  PARAM_VEHICAL_NUMBER:"vehical_number",
  PARAM_CREATED_BY:"created_by",
  PARAM_MODIFY_BY:"modify_by",
  PARAM_CAST_ID:"cast_id",
  PARAM_MARRITAL_STATUS_ID:"marrital_status_id",
  PARAM_MARRIAGE_CITY_ID:"marrital_status_id",
  PARAM_BLOOD_GROUP_ID:"blood_group_id",
  PARAM_GENDER:"gender",
  PARAM_USERCODE: "user_code",
  PARAM_RESOURCE_PERMISSION_TYPE_ID: "resource_permission_type_id",
  PARAM_SURVEY_ID : "survey_id",
  PARAM_SURVEY_TITLE : "survey_title",
  PARAM_SURVEY_DESCRIPTION : 'survey_description',
  PARAM_SURVEY_QUESTION_LIMIT: 'survey_question_limit',
  PARAM_START_DATETIME: 'start_datetime',
  PARAM_END_DATETIME: "End_datetime",
  PARAM_SURVEY_DEPT_RECIPIENT_ID : "survey_department_recipient_id",
  PARAM_DEPARTMENT_MAPPING_ID : "department_mapping_id",
  PARAM_USER_CODE : "user_code",
  PARAM_BUSINESS_UNIT_ID: "business_unit_id",
  PARAM_DIVISION_ID: "division_id",
  PARAM_DEPARTMENT_ID: "department_id",
  PARAM_GROUP_ID: "group_id",
  PARAM_SURVEY_DEPARTMENT_RECIPIENT_ID: "survey_department_recipient_id",
  PARAM_SURVEY_QUESTION_ID: "survey_question_id",
  PARAM_QUESTION_TITLE : "question_title",
  PARAM_QUESTION_DESCRIPTION : "question_description",
  PARAM_QUESTION_ORDER_ID : "question_order_id",
  PARAM_IS_ACTIVE : "is_active",
  PARAM_IS_MANDATORY : "is_mandatory",
  PARAM_SURVEY_QUESTION_TYPE_ID : "survey_question_type_id",
  PARAM_QUESTION_TYPE_ID : "question_type_id",
  PARAM_SURVEY_QUESTION_VALUE_ID : "survey_question_value_id",
  PARAM_QUESTION_VALUE : "question_value",
  PARAM_IS_RIGHT_ANSWER : "is_right_answer",
  PARAM_SURVEY_QUESTION : "Survey_Question",
  PARAM_SURVEY_QUESTION_TYPES : "Survey_question_types",
  PARAM_SURVEY_QUESTION_VALUES : "Survey_question_values",
  PARAM_TABLE_NAME :"table_name",
  PARAM_SURVEY_QUESTION_ORDER_ID:"question_value_order_id",
  PARAM_SURVEY_QUESTION_TYPES_ID: "survey_question_types_id",
  //***********************Store Procedure*************************//
  SP_USERWISE_RESPONDEDDATA_LIST: "usp_user_wise_respondedData_fill",
  SP_CONTROLCENTER_USERS_UPSERT: "usp_Controlcenter_Users_upsert",
  SP_SURVEY_SUMMARY_LIST: "usp_survey_summary",
  SP_SURVEY_GET_LIS: "usp_survey_publishSurvey_getautopopulate",
  SP_SURVEY_QUESTION_UPSERT: "usp_Survey_Question_Upsert",
  SP_SURVEY_QUESTION_DELETE: "usp_Survey_Question_Delete",
  SP_EMPLOYEE_UPSERT: "usp_employee_upsert",
  SP_EMPLOYEE_DELETE: "usp_employee_delete",
  SP_EMPLOYEE_DETAILS : "usp_employee_fill",
  SP_SURVEY_INFO_UPSERT : "usp_survey_info_upsert",
  SP_SURVEYLIST : "usp_survey_info_list",
  SP_SURVEY_DELETE:"usp_survey_delete",
  SP_SURVEY_INSERT_READ_RECEIPTS : "usp_survey_insert_read_receipts",
  SP_SURVEY_ANS_LIST:"usp_survey_ans_fill",
  SP_SURVEY_AUTOPOPULATE:"usp_survey_publishSurvey_getautopopulate",
  SP_OUTPUT:"usp_output"
};
